### ISSUE TITLE
possible cvx license violation

### ISSUE THREAD

**Issue by DenisPolygalov** [JinghaoLu/MIN1PIPE#1]
Hi JinghaoLu,
I advice you to get advice from your lawer because to my limited knowledge this repository contain code that can not be re-destributed freely. So people who will re-use it may have legal problems.

From: https://github.com/JinghaoLu/MIN1PIPE/tree/master/utilities/cvx

"
This package is governed by the terms of the CVX Professional License. This
package may *not* be redistributed or placed in a public repository without
the advance written consent of CVX Research, Inc.
"

Also you giving away binary *.p files with *your* license information to everyone. :) 

Regards,
Denis.

**Comment by JinghaoLu** [comment]
Hi Denis,

Thanks for raising the concern. I removed the package from this repo. 

J
