### ISSUE TITLE
Error using intra_section (line 67)

### ISSUE THREAD

**Issue by ivosonntag** [JinghaoLu/MIN1PIPE#10]
I get the following error message when the code returns the line 'Begin intra-section '. This is the case for both the demo, as well as for UCLA Miniscope datasets. The path should be 'clean', and I used the latest version of the code (27.11.2018). Some of the calculations are running on a gpu.

Error using intra_section (line 67)
Cannot index into 'reg' because indices cannot be empty.

Error in frame_reg (line 87)
    m = intra_section(m, stt, stp, pixs, scl, sigma_x, sigma_f, sigma_d, flag);

Error in min1pipe (line 102)
                [m, corr_score, raw_score, scl] = frame_reg(m, imaxy, se, Fsi_new, pixs, scl, sigma_x, sigma_f, sigma_d);

**Comment by JinghaoLu** [comment]
The bug is fixed.

**Comment by ivosonntag** [comment]
Works great now!
