### ISSUE TITLE
Miniscope video with 24 bits per pixel

### ISSUE THREAD

**Issue by KarolinaFarrell** [JinghaoLu/MIN1PIPE#11]
I've tried running the code on my Miniscope imaging video (.avi), the code gets stuck in data_cat.m when trying to use zeros because the VideoReader gets 24 bits per pixel and therefore dtype becomes 'uint24'. How can I get around this without corrupting my data? Thanks!

**Comment by JinghaoLu** [comment]
Hi Karolina,

I am not sure what the problem is without more information. If it is possible, do you mind sending a small piece of demo video so that I can try reproducing the problem and finding a solution?

Jinghao

**Comment by KarolinaFarrell** [comment]
I've sent it to min1pipe2018@gmail.com. Thanks!
