### ISSUE TITLE
Error with video from miniscope

### ISSUE THREAD

**Issue by qjtang12** [JinghaoLu/MIN1PIPE#15]
Hello Jinghao,

I am new to your package. When I try to test it out using demo. I got the Error as below. 

Error using griddedInterpolant
Interpolation requires at least two sample points in each dimension.

Error in interp1 (line 151)
        F = griddedInterpolant(X,V,method);

Error in get_trans_score (line 91)
        acorr(idss) = interp1(ids, acorr(ids), idss, 'pchip', 'extrap');

Error in frame_reg (line 80)
        acorr(max(1, idbatch(i) - 1): idbatch(i + 1) - 2) = get_trans_score(tmp, [], 1, 1, mq, maskc);

Error in min1pipe (line 102)
                [m, corr_score, raw_score, scl] = frame_reg(m, imaxy, se, Fsi_new, pixs, scl, sigma_x,
                sigma_f, sigma_d);

**Comment by JinghaoLu** [comment]
What video are you using? Is it demo video or a video from your study? The direct cause to me is that the algorithm could not calculate the movement score from any pair of your video, possibly indicating that there is no salient feature/information to track with. It would be good if I can take a look at some demo frames of your video.

**Comment by qjtang12** [comment]
Download full resolution images
Available until Apr 6, 2019
 <https://www.icloud.com/attachment/?u=https%3A%2F%2Fcvws.icloud-content.com%2FB%2FAYD3P_aaY4k30CeyPiMWuot1djc_AVyVuxB-yfPsDHiqumXtxDmUzBAH%2F%24%7Bf%7D%3Fo%3DAkODHKvFAaNNKc0G3saezFSivYiBSftLdCaI2A3ZsbHL%26v%3D1%26x%3D3%26a%3DB7S_RaZSJT38irFTc5ArQdYWbexUA5ZUSgEACAHIAP9SL6uVA9arSQ%26e%3D1554583062%26k%3D%24%7Buk%7D%26fl%3D%26r%3DF77896B5-CE3C-4D2A-8042-5D7BB328B0AD-1%26ckc%3Dcom.apple.largeattachment%26ckz%3D07CA434D-69DD-4458-9A41-22C0384EB4BF%26p%3D53%26s%3DtIRPNiax12pL5Ga-G8cEs-9mWSI&uk=BpsXbzjxFwxw95TPZZlQ6w&f=Images.zip&sz=42354962>Hello Jinghao,

Thank you for getting back to me so quickly.
I am use my own video recorded by UCLA miniscope. Regarding you explain, that sounds because my video quality is too bad. The reason why you see this shitty video is because my recording region is a little bit too deep. I am working on improving it too, if the script error can be solved by enhancing video quality.
I have attached the video I ran yesterday. 



Qijun Tang

**Comment by JinghaoLu** [comment]
Hi Qijun,

I tested the video you provided, and it worked all well through the algorithm on my machine. I think improving imaging quality exactly solves the problem.

**Comment by qjtang12** [comment]
Hi Jinghao,

I am so sorry. I should have done this at very beginning but I just figured it out. The matlab on lab computer is lacking two packages. The problem could be either from the lack of Computer Vision System Toolbox or Curve Fitting Toolbox.

Thank you for helping me and thank you for your work.

Qijun
