### ISSUE TITLE
Issue with plot_contour.m

### ISSUE THREAD

**Issue by sstaszko** [JinghaoLu/MIN1PIPE#17]
When I attempt to run the plot_contour postprocess script, I get the following: 

Not enough input arguments.

Error in plot_contour (line 6)
    [x, y] = ind2sub([pixh, pixw], seedsfn);
 
pixh, pixw, and seedsfn are all loaded into the workspace.

**Comment by JinghaoLu** [comment]
I guess you have another ind2sub function other than matlab built-in exists in your path.
