### ISSUE TITLE
Error in par_init (line 8)

### ISSUE THREAD

**Issue by ericajrodriguez** [JinghaoLu/MIN1PIPE#18]
Hi Jinghao, 
 
I keep getting this error when I run min1pipe (on matlab 2018b, windows 10): 

Done pix select, time: 2.1379 seconds
Error using preprocess_data (line 57)
MatFile objects are scalar. Access variables using the syntax objName.varName(indices).

Error in par_init (line 8)
    P = preprocess_data(m);

Error in min1pipe (line 130)
            [P, options] = par_init(m);

Error in ROIextraction (line 12)
    [fname,frawname,fregname] = min1pipe(Fsi, Fsi, 1, se, ismc);

Do you have any suggestions? 

Thanks!
Erica

**Comment by JinghaoLu** [comment]
Hi Erica,

I think you probably have another preprocess_data in your matlab path. See #9 

Thanks,

Jinghao

**Comment by ericajrodriguez** [comment]
Thank you Jinghao! I removed the preprocess_data from another folder on the matlab path and it works now.
