### ISSUE TITLE
Index exceeds the number of array elements (345465856).

### ISSUE THREAD

**Issue by myhuyong** [JinghaoLu/MIN1PIPE#19]
Hi Jinghao Lu,
Recently, when I test my avi video from miniscope in MATLAB R2019a, I get an error message "Index exceeds the number of array elements (345465856)". Do you have any suggestion to fix this? Thank you.
Yong

**Comment by JinghaoLu** [comment]
Hi Yong,

Please provide the detailed error message, including at which step and function it comes from.

Thanks

**Comment by myhuyong** [comment]
Hi Jinghao Lu,
Following is the error message. Thank you!
Yong

Begin collecting datasets info
Done collecting datasets info, time: 0.48848
Begin data cat
Index exceeds the number of array elements (360988160).

Error in data_cat (line 187)
                            frame = flipud(reshape(d_raw(stt(f_idx(ii)) + 1: stt(f_idx(ii)) + ndframe), pixwo, pixho)');

Error in min1pipe (line 83)
            [m, filename_raw, imaxn, imeanf, pixh, pixw, nf] = data_cat(path_name, file_base{i}, file_fmt{i}, Fsi, Fsi_new,
            spatialr);

Error in demo_min1pipe (line 14)
[fname, frawname, fregname] = min1pipe(Fsi, Fsi_new, spatialr, se, ismc, flag);

Error in run (line 91)
evalin('caller', strcat(script, ';'));

**Comment by JinghaoLu** [comment]
Thanks for bringing this up. It is due to a recent bug after fixing the avi reading index issue, which is now corrected and updated in the git repo.
