### ISSUE TITLE
Cell detection in Min1pipe

### ISSUE THREAD

**Issue by akatav** [JinghaoLu/MIN1PIPE#34]
HI,
So, below is a sample gif from one of the sessions recorded from mouse brain.There are no visible  neurons as can be seen. But Min1pipe detects 100+ cells in this data.I'd like to know how min1pipe detects these many neurons in this dataset.Does min1pipe return a default number of neurons for a given brain region by any chance?Kindly explain.
![test1](https://user-images.githubusercontent.com/721570/80162658-dfc33d80-860e-11ea-810f-772252db585e.gif)

**Comment by JinghaoLu** [comment]
The answer to your question is no. BTW, your video provoked, so you'd better ask the video for an explanation. [Good luck](https://github.com/JinghaoLu/MIN1PIPE/blob/master/utilities/wrong_place_out!/Question_Guide)!

**Comment by akatav** [comment]
@JinghaoLu  sorry about that.i agree that i did not give much info about the video itself although i am not sure what is provocative about it.it is a sample gif from one of our sessions recorded from mouse brain.

**Comment by JinghaoLu** [comment]
Anyway. Feel free to share the parameters you used so that I can see what is going on, if you still have interest.
