### ISSUE TITLE
CVX error on initial download

### ISSUE THREAD

**Issue by hlhorsnellphd** [JinghaoLu/MIN1PIPE#36]
Hello, 

New to MATLAB and programming, I received this error message (attached in picture) and I can't seem to resolve!

![Screenshot 2020-05-12 at 15 50 31](https://user-images.githubusercontent.com/65238962/81707167-5a41e900-9468-11ea-9ced-c88faa6a8e41.png)

Do you have any suggestions?

Thanks for your time

Harry

**Comment by JinghaoLu** [comment]
How did you set up MIN1PIPE? Usually cvx errors are due to incorrect installation of MIN1PIPE. Check [this](https://github.com/JinghaoLu/MIN1PIPE#usage) out.

**Comment by hlhorsnellphd** [comment]
resolved, thanks!
