### ISSUE TITLE
Error in registration

### ISSUE THREAD

**Issue by rajatsaxena** [JinghaoLu/MIN1PIPE#40]
I am using the demo.tif provided in the dataset and running the `min1pipe.m` script. This is the error message that I get.. How can I resolve this? Thank you

```
Error using intra_section (line 76)
Expected BlockSize to be an array with all of the values >= 5.

Error in frame_reg (line 92)
        m = intra_section(m, stt, stp, pixs, scl, sigma_x, sigma_f, sigma_d, flag, maskc);

Error in min1pipe (line 108)
                    [m, corr_score, raw_score, scl] = frame_reg(m, imaxy, se, Fsi_new, pixs, scl,
                    sigma_x, sigma_f, sigma_d);
```

**Comment by JinghaoLu** [comment]
Did you install all the packages? Like computer vision toolbox?

**Comment by rajatsaxena** [comment]
yes all the dependencies are installed

**Comment by JinghaoLu** [comment]
A first guess would be that somehow, you have some bad pixels at the boundaries/corners of the field of view, that are of high values. If not, then you might need to set a break point at where you have the problem, and run the program to find out the exact problem.

**Comment by rajatsaxena** [comment]
I am running it on the demo.tif file provided in the repo

**Comment by JinghaoLu** [comment]
oh right I forgot this. Did you spatially downsample the video? For demo.tif you don't need to downsample.

**Comment by rajatsaxena** [comment]
No, I did not do any downsampling. Just used the default params.

**Comment by JinghaoLu** [comment]
I don't think I have any quick answer to this then. This should not happen, and the only way to know what exactly the problem is is to set a breakpoint and see what triggers this on your machine.

**Comment by rajatsaxena** [comment]
I had to just reinstall everything and it worked. Sorry for the trouble
