### ISSUE TITLE
 Undefined function 'cvx_begin' for input arguments of type 'char'.

### ISSUE THREAD

**Issue by Mtkostecki** [JinghaoLu/MIN1PIPE#48]
Hi,

I'm trying to run demo_min1pipe, yet almost at the beginning I get the error:

> Analyzing and transferring files to the workers ...done.
> Error using refine_roi (line 69)
> The source code (C:\Users\mkostecki\Documents\MATLAB\MIN1PIPE-master\utilities\elements\refine_roi.m) for the parfor-loop
> that is trying to execute on the worker could not be found.
> 
> Error in iter_seeds_select (line 33)
>         [roirf, sigupdt, seedsupdt, datasmthf1, cutofff1, pkcutofff1] = refine_roi(m_tmp, sig, bgf, roi, seeds, noise, datasmth0,
>         cutoff0, pkcutoff0, ispara);
> 
> Error in min1pipe_HPC (line 137)
>             [sigrf, roirf, seedsupdt, bgrf, bgfrf, datasmthf1, cutofff1, pkcutofff1] = iter_seeds_select(m, mask, Params, P,
>             options, flag);
> 
> Error in demo_min1pipe_HPC (line 19)
> [fname, frawname, fregname] = min1pipe_HPC(Fsi, Fsi_new, spatialr, se, ismc, flag, path_name, file_name);
> 
> Caused by:
>     Undefined function 'cvx_begin' for input arguments of type 'char'.
>     Error using remoteParallelFunction (line 84)
>     Worker unable to find file.
>         Undefined function 'cvx_begin' for input arguments of type 'char'.

In fact, a function refine_roi.m exists definitely within a specified directory. What is the problem?

**Comment by JinghaoLu** [comment]
Hi, please refer to [this](https://github.com/JinghaoLu/MIN1PIPE#usage). Do not manually include any folders in the matlab path. Instead, let the program do it.
