### ISSUE TITLE
Error after neural enhancing

### ISSUE THREAD

**Issue by Mtkostecki** [JinghaoLu/MIN1PIPE#52]
Hi!

I have met an error after a neural enhancing step, what may be a cause?

> 
Done noise suppression, time 106.348
No GPU Device available.
Insufficient number of outputs from right hand side of equal sign to satisfy assignment.

Error in dominant_patch (line 16)
    bb = bb.BoundingBox;

Error in frame_reg (line 53)
    mskpre = dominant_patch(imaxn, dthres);

Error in min1pipe (line 108)
                    [m, corr_score, raw_score, scl, imaxy] = frame_reg(m, imaxy1, se, Fsi_new, pixs, scl, sigma_x, sigma_f,
                    sigma_d);

Error in demo_min1pipe (line 14)
[fname, frawname, fregname] = min1pipe(Fsi, Fsi_new, spatialr, se, ismc, flag);

>>

**Comment by JinghaoLu** [comment]
Hi, it seems likely that the algorithm did not successfully find a patch that contains the neural info there. Could you mind sending the max projection figure after neural enhancing for example? You can send it to min1pipe2018@gmail.com.

**Comment by Mtkostecki** [comment]
I have fixed that - it turned out that my first two tif files were broken for some reason.
