### ISSUE TITLE
Interpolation issue with interp1

### ISSUE THREAD

**Issue by SelenaLG** [JinghaoLu/MIN1PIPE#74]
I catch an error concerning interp1 during I was running minipipe.p.
![Capture d'écran 2024-06-18 170515](https://github.com/JinghaoLu/MIN1PIPE/assets/157131127/bb5b632c-da41-47ae-bed7-a80bdc24556e)

I don't understand really well interpolation and there is no official documentation for this function. Some errors were reported on Matlab forum concerning this function but it is on other errors.

**Comment by JinghaoLu** [comment]
This is usually not the issue with interp1 (btw interp1 is a matlab function so there is a document on it), but something in your data. For example, you can check if your video contains some dead bright pixel, and perhaps the preprocessing steps does not return correct result because of this.

**Comment by SelenaLG** [comment]
Yes, I found the origin of the issue. accor is full of Nan at a moment so ~isnan(acorr) become a matrix full of zeros. And I don't know how find function supports this case because I tried to display ids and nothing appear (no display and no error) but I think it becomes something like None in Python. And it causes the error.

What is the best way to manage this case ?

**Comment by JinghaoLu** [comment]
You can check the output .mat file **_reg.mat, and see if variable reg contains valid preprocessed frames. Also you need to first make sure if you have all the dependent toolboxes installed.

**Comment by SelenaLG** [comment]
So I just forgot to install some toolboxes 😅, now it runs well !
