### ISSUE TITLE
Error with video from Miniscope

### ISSUE THREAD

**Issue by myhuyong** [JinghaoLu/MIN1PIPE#8]
When running min1pipe.m, I get the following error.

Error using frame_reg
Too many input arguments.

Error in min1pipe (line 102)
                [m, corr_score, raw_score, scl] = frame_reg(m, imaxy, se, Fsi_new, pixs, scl, sigma_x, sigma_f, sigma_d);

Error in run (line 91)
evalin('caller', strcat(script, ';'));

**Comment by JinghaoLu** [comment]
This results from the archived MIN1PIPE_v1 being in the matlab path, which uses a different version of "frame_reg". You can remove "_archive/MIN1PIPE_v1" from matlab path or delete that folder from the hard disk. I removed it from the repository as well so no conflicting functions co-exist.
